<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="es"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Revisión Técnica</title>
        <link rel="shortcut icon" href=" favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/redmond/jquery-ui-1.10.4.custom.min.css" />
        <link rel="stylesheet" href="css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="css/main.css">
    </head>
    <body >
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <?php require '../util/nav.phtml'; ?>
        
        <!-- Main jumbotron for a primary marketing message or call to action -->

        <div class="container">
            <!-- Example row of columns -->
            <?php if ($flashes): ?>
                <ul class="alert alert-success list-unstyled" id="flashes">
                    <?php foreach ($flashes as $flash): ?>
                        <li><h4><?php echo $flash; ?></h4></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?php require $template; ?>

        </div>
        <hr></hr>
        <div class="container">
            <p>V10.00 <a href="http://www.gestion-e.com.ar/">Gestión-e</a>, 2016 &copy; Gestión-e SRL - Todos los derechos reservados</p>
        </div>

         <!-- Modal -->
  <div class="modal fade" id="modalSalir" role="dialog">
    <div class="modal-dialog modal-sm" style="width:300px">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="background-color: rgb(167, 29, 0);color:white !important;text-align:center;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4>¿Desea salir del sistema?</h4>
        </div>
        <div class="modal-body" >
          
        </div>
        <div class="modal-footer">
            <a href="<?php echo Utils::createLink('logout'); ?>" class="btn btn-danger btn-block" type="button">Confirmar</a>
        </div>
      </div>
    </div>
 </div>
 
        <script src="js/vendor/jquery-1.10.2.js"></script>
        <script src="js/vendor/bootstrap.min.js"></script>
        <script src="js/vendor/jquery-ui-1.10.4.custom.min.js"></script>
        <script src="js/main.js"></script>

    </body>
</html>
