<?php
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2013 Gestión-e - Gestión Informática Eficiente. All rights reserved.
 *
 *
 */

//~ Template for list.php
// variables:
//  $title - page title
//  $status - status of TODOs to be displayed
//  $todos - TODOs to be displayed
?>

<h1>
    Cámara Enviada
</h1>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Seleccione un criterio de filtro</h3>
    </div>
    <div class="panel-body">
        <form name="input" class="form-inline" role="form" action="index.php" method="get" >
            <fieldset>
                <div class="row">
                    <input type="hidden"  name ='page' value="envlista"/>

                    <div class="form-group col-md-1">
                    <label for="centro">Centro:</label>
                        <input type="text" class="form-control form-sm" name="centro" id="centro" value="<?php echo $centro;?>" size="3" >
                    </div>

                    <div class="form-group col-md-1">
                    <label for="sucdep">Suc.Dep.:</label>
                        <input type="text" class="form-control form-sm" name="sucdep" id="sucdep" value="<?php echo $sucdep;?>" size="3" >
                    </div>

                    <div class="form-group col-md-1">
                    <label for="Ent">Ent:</label>
                        <input type="text" class="form-control form-sm" name="ent" id="ent" value="<?php echo $ent;?>" size="3" >
                    </div>

                    <div class="form-group col-md-1">
                    <label for="suc">Suc:</label>
                        <input type="text" class="form-control form-sm" name="suc" id="suc" value="<?php echo $suc;?>" size="3" >
                    </div>

                    <div class="form-group col-md-1">
                    <label for="cp">CP:</label>
                        <input type="text" class="form-control form-sm" name="cp" id="cp" value="<?php echo $cp;?>" size="4" >
                    </div>

                    <div class="form-group col-md-1">
                    <label for="nro">Nro:</label>
                        <input type="text" class="form-control form-sm" name="nro" id="nro" value="<?php echo $nro;?>" size="8" >
                    </div>

                    <div class="form-group col-md-1">
                    <label for="cta">Cta:</label>
                        <input type="text" class="form-control form-sm" name="cta" id="cta" value="<?php echo $cta;?>" size="11" >
                    </div>

                    <div class="form-group col-md-1">
                    <label for="importe">Imp.mín.:</label>
                        <input type="text" class="form-control form-sm" name="importe" id="importe" value="<?php echo $importe;?>"  size="8" >
                    </div>

                    <div class="form-group col-md-2">
                        <label for="estado">Estado:</label> 
                        <select id="estado" class="form-control form-sm"  type="text" name="estado" >
                            <?php foreach ($estados as $key => $est): ?>
                                <option value="<?php echo $key; ?>"
                                <?php if ($key == $estado): ?>
                                            selected="selected"
                                <?php endif; ?>
                                        ><?php echo $est; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    
                    <div class="form-group col-md-2">
                        <br>
                        <input type="submit" class="btn btn-primary form-control"  value="Aplicar"/>
                    </div>
                </div>

                <div class="row">
                    <ul class="pager">
                        <li class="previous">
                            <BUTTON <?php echo ($pagina == 0) ? 'disabled' : '' ?> name="first" value="first" title="Primera página" type="submit" class="btn btn-default"><<</BUTTON>
                        </li>
                        <li class="previous">
                            <BUTTON <?php echo ($pagina == 0) ? 'disabled' : '' ?> name="prev" value="prev" title="Página anterior" type="submit" class="btn btn-default"><</BUTTON>
                        </li>
                        <li >
                            <BUTTON disabled title="" type="submit" class="btn btn-default">Página <?php echo $pagina + 1 ?> de <?php echo $paginas + 1 ?></BUTTON>
                        </li>
                        <li class="next">
                            <BUTTON <?php echo ($pagina == $paginas) ? 'disabled' : '' ?> name="next" value="next" title="Página siguiente" type="submit" class="btn btn-default">></BUTTON>
                        </li>
                        <li class="next">
                            <BUTTON <?php echo ($pagina == $paginas) ? 'disabled' : '' ?> name="last" value="last" title="Última página" type="submit" class="btn btn-default">>></BUTTON>
                        </li>
                    </ul>
                </div>
                </div>
                </div>

                <input type="hidden"  name ='pagina' value="<?php echo $pagina; ?>"/>

                <br/>

                <table  class="table table-striped table-hover table-condensed">
                    <thead>
                        <tr>
                            <th scope="col">Centro</th>
                            <th scope="col">SucDep</th>
                            <th scope="col">Ent</th>
                            <th scope="col">Suc</th>
                            <th scope="col">CP</th>
                            <th scope="col">Número</th>
                            <th scope="col">Cuenta</th>
                            <th scope="col">Importe</th>
                            <th scope="col">Estado</th>
                            <th scope="col">Rechazos</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($documentos as $key => $documento): ?>
                            <tr>
                                <td><?php echo $documento->getDepcentro(); ?></td>
                                <td><?php echo $documento->getDepsuc(); ?></td>
                                <td><?php echo $documento->getEnt(); ?></td>
                                <td><?php echo $documento->getSuc(); ?></td>
                                <td><?php echo $documento->getCp(); ?></td>
                                <td><?php echo $documento->getNro(); ?></td>
                                <td><?php echo $documento->getCta(); ?></td>
                                <td><?php echo Utils::formatMoney($documento->getImporte()); ?></td>
                                <td><img src="img/icono/ESTADO<?php echo $documento->getEstado(); ?>.png">
                                <?php echo $documento->getEstadoFormat(); ?></td>
                                <td><?php echo implode(',',$documento->getRechazos()); ?></td>
                                <td align="center"><a href="
                                <?php echo Utils::createLink('envrev', array(
                                            'centro' => $centro, 
                                            'sucdep' => $sucdep,
                                            'ent'    => $ent,
                                            'suc'    => $suc,
                                            'cp'     => $cp,
                                            'nro'    => $nro,
                                            'cta'    => $cta,
                                            'importe'=> $importe,
                                            'fecha'  => $fecha,
                                            'estado' => $estado, 
                                            'idx' => $key+($pagina*$REGISTROS))); ?>">
                                <img src="img/icono/Z1.png" alt="" title="Revisar este documento" class="icon" /></a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <br>
                <div class="panel panel-default">

                    <div class="panel-body">
                        <div class="row">
                            <ul class="pager">
                                <li class="previous">
                                    <BUTTON <?php echo ($pagina == 0) ? 'disabled' : '' ?> name="first" value="first" title="Primera página" type="submit" class="btn btn-default"><<</BUTTON>
                                </li>
                                <li class="previous">
                                    <BUTTON <?php echo ($pagina == 0) ? 'disabled' : '' ?> name="prev" value="prev" title="Página anterior" type="submit" class="btn btn-default"><</BUTTON>
                                </li>
                                <li >
                                    <BUTTON disabled title="" type="submit" class="btn btn-default">Página <?php echo $pagina + 1 ?> de <?php echo $paginas + 1 ?></BUTTON>
                                </li>
                                <li class="next">
                                    <BUTTON <?php echo ($pagina == $paginas) ? 'disabled' : '' ?> name="next" value="next" title="Página siguiente" type="submit" class="btn btn-default">></BUTTON>
                                </li>
                                <li class="next">
                                    <BUTTON <?php echo ($pagina == $paginas) ? 'disabled' : '' ?> name="last" value="last" title="Última página" type="submit" class="btn btn-default">>></BUTTON>
                                </li>
                            </ul>
                        </div>
                        </filedset>
                        </form>
                        <br>
                        <div class="row" align="center">
                            <?php if ($modifica): ?>
                                <a href="<?php echo Utils::createLink('envrev',array('e' => 'p', 'i' => 0)); ?>" type="button" class="btn btn-primary">Revisar pendientes</a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
