<?php
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2013 Gestión-e - Gestión Informática Eficiente. All rights reserved.
 *
 *
 */
?>
<h1>Ayuda para la página de inicio</h1>

<div class="row">
    <div class="col-md-12">
        <br>
    <p>Esta es la página de ingreso al sistema. </p>
    <p>Por favor utilice el menú de la barra superior para acceder a cada una de las distintas funciones.</p>
    <p>El sistema de ayuda estará disponible en cada una de las páginas a las que acceda.</p>
    
    <img src="./img/help/menu.png" title="" style="border: solid blue" class="img-responsive"/><br/>
    <ol>
        <li><strong>Inicio:</strong> le permite acceder a la página de inicio al sistema</li>
        <li><strong>Ayuda:</strong> en todo momento podrá contar con una página de ayuda de acuerdo a la función que esté utilizando</li>
        <li><strong>Cobrar:</strong> si su perfil se lo permite, podrá acceder al menú de cobranzas<br><br>
        <img src="./img/help/menu-cobrar.png" title="" style="border: solid blue" class="img-responsive"/><br/>
        <ul>            
            <li>Documentos: aquí podrá consultar y gestionar todas las facturas y otros documentos a cobrar</li>
            <li>Pagos recibidos: le permitirá consultar y administrar las órdenes de pago emitidas por sus clientes para su empresa</li>
            <li>Mensajes: le permite acceder al buzón de mensajes intercambiados con clientes</li>
            <li>Reportes: acceda aquí para emitir los reportes de cobrador</li>
            <li>Importar cuentas a cobrar: usted puede ingresar información al sistema en forma manual o automática.<br> 
                Ingresando en esta opción podrá cargar automáticamente la información que desee de sus cuentas a cobrar. </li>
        </ul>
        </li>
        <li><strong>Pagar:</strong> si su perfil se lo permite, podrá acceder al menú de pagos a proveedores<br><br>
        <img src="./img/help/menu-pagar.png" title="" style="border: solid blue" class="img-responsive"/><br/>
        <ul>            
            <li>Documentos: aquí podrá consultar y gestionar todas las facturas y otros documentos, emitidos por sus proveedores, a pagar </li>
            <li>Pagos emitidos: le permitirá consultar y administrar las órdenes de pago que haya emitido para los proveedores de su empresa</li>
            <li>Mensajes: le permite acceder al buzón de mensajes con proveedores</li>
            <li>Reportes: acceda aquí para emitir los reportes de pagos a proveedores</li>
            <li>Importar cuentas a pagar: usted puede ingresar información al sistema en forma manual o automática.<br> 
                Ingresando en esta opción podrá cargar automáticamente la información que desee de sus cuentas a pagar. </li>
        </ul>
        </li>
        <li><strong>Mensajes:</strong> le permitirá acceder a su bandeja de mensajes con proveedores y clientes.</li>
        <li><strong>Administrar usuarios:</strong> si usted es un usuario administrador, aquí podrá gestionar los usuarios de su empresa y de sus proveedores y clientes</li>
        <li><strong>Clave de acceso:</strong> haciendo clic aquí podrá acceder a las siguientes acciones<br><br>
        <img src="./img/help/menu-usuario.png" title="" style="border: solid blue" class="img-responsive"/><br/>
        <ul>            
            <li>Cambiar contraseña: su contraseña es personal y nunca deberá ser divulgada. Le recomendamos que la cambie habitualmente para garantizar la privacidad de la información de su empresa</li>
            <li>Salir: le permite salir del sistema en forma segura. Todo nuevo intento de acceso requerirá el ingreso de usuario y contraseña.</li>
        </ul>
        </li>
    </ol>
</div>
    </div>
<div class="row">
    <div class="col-md-12">
        <br/>
        <br/>
        <a href="<?php echo Utils::createLink('home'); ?>" type="button" class="btn btn-primary">Volver a la página de inicio</a>
</div>
    </div>

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
