<div class="container">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <form class="form-signin" action="#" method="POST">
        <h2 class="form-signin-heading">Por favor, ingrese sus credenciales</h2>
        <label for="username">Usuario: </label><input id="username" type="text" name="username"  
             class="form-control" placeholder="Usuario" required autofocus/> 
        <label for="password">Contraseña: </label><input id="password" type="password" name="password" 
             class="form-control" placeholder="Contraseña" required/>
        <div class="row" align="center"><br></div>
        <button class="btn btn-lg btn-primary btn-block" type="submit" name="submit">Ingresar</button>
        
      </form>
      <div class="row" align="center">
         <h3><?php echo $msg; ?></h3>
      </div> <!-- /row -->
    </div>
    <div class="col-md-3">
    </div>
</div> <!-- /container -->