<?php
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2013 Gestión-e - Gestión Informática Eficiente. All rights reserved.
 *
 *
 */

//~ Template for list.php
// variables:
//  $title - page title
//  $status - status of TODOs to be displayed
//  $todos - TODOs to be displayed
?>

<h1>
    Registro de auditoría
</h1>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Seleccione un criterio de filtro</h3>
    </div>
    <div class="panel-body">
        <form name="input" class="form-inline" role="form" action="index.php" method="get" >
            <fieldset>
                <div class="row">
                    <input type="hidden"  name ='page' value="loglista"/>

                    <div class="form-group col-md-1">
                    <label for="secuencia">Secuencia:</label>
                        <input type="text" class="form-control" name="secuencia" id="secuencia" value="<?php echo $secuencia;?>"  >
                    </div>

                    <div class="form-group col-md-2">
                    <label for="fecha">Fecha:</label>
                        <input id="fecha" type="text" name="fecha" class="text datepicker form-control"  value="<?php echo $fecha; ?>"/>
                    </div>

                    <div class="form-group col-md-2">
                    <label for="usuario">Usuario:</label>
                        <input type="text" class="form-control" name="usuario" id="usuario" value="<?php echo $usuario;?>">
                    </div>

                    <div class="form-group col-md-1">
                    <label for="ip">IP:</label>
                        <input type="text" class="form-control" name="ip" id="ip" value="<?php echo $ip;?>">
                    </div>

                    <div class="form-group col-md-1">
                    <label for="evento">Evento:</label>
                        <input type="text" class="form-control" name="evento" id="evento" value="<?php echo $evento;?>">
                    </div>

                    <div class="form-group col-md-2">
                    <label for="clave">Clave:</label>
                        <input type="text" class="form-control" name="clave" id="clave" value="<?php echo $clave;?>">
                    </div>

                    <div class="form-group col-md-2">
                        <br>
                        <input type="submit" class="btn btn-primary form-control"  value="Aplicar"/>
                    </div>
                    <div class="form-group col-md-1">
                        <br>
                        <BUTTON name="bajar" class="btn btn-default form-control" value="bajar" title="Bajar los documentos filtrados a una planilla Excel" type="submit"  ><IMG src="./img/icono/XLS.jpg" style="width: 20px"></BUTTON>
                    </div>
                </div>

                <div class="row">
                    <ul class="pager">
                        <li class="previous">
                            <BUTTON <?php echo ($pagina == 0) ? 'disabled' : '' ?> name="first" value="first" title="Primera página" type="submit" class="btn btn-default"><<</BUTTON>
                        </li>
                        <li class="previous">
                            <BUTTON <?php echo ($pagina == 0) ? 'disabled' : '' ?> name="prev" value="prev" title="Página anterior" type="submit" class="btn btn-default"><</BUTTON>
                        </li>
                        <li >
                            <BUTTON disabled title="" type="submit" class="btn btn-default">Página <?php echo $pagina + 1 ?> de <?php echo $paginas + 1 ?></BUTTON>
                        </li>
                        <li class="next">
                            <BUTTON <?php echo ($pagina == $paginas) ? 'disabled' : '' ?> name="next" value="next" title="Página siguiente" type="submit" class="btn btn-default">></BUTTON>
                        </li>
                        <li class="next">
                            <BUTTON <?php echo ($pagina == $paginas) ? 'disabled' : '' ?> name="last" value="last" title="Última página" type="submit" class="btn btn-default">>></BUTTON>
                        </li>
                    </ul>
                </div>
                </div>
                </div>

                <table  class="table table-striped table-hover table-condensed">

                    <thead>
                        <tr>
                            <th >Secuencia</th>
                            <th >Fecha</th>
                            <th >Usuario</th>
                            <th >IP</th>
                            <th >Evento</th>
                            <th >Clave</th>
                            <th >Datos</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach ($registros as $registro): ?>
                            <tr>
                                
                                <td><?php echo $registro->getId(); ?></td>
                                <td><?php echo Utils::formatDateTime($registro->getFechahora()); ?></td>
                                <td><?php echo $registro->getUsuario(); ?></td>
                                <td><?php echo $registro->getIp(); ?></td>
                                <td><?php echo $registro->getEvento(); ?></td>
                                <td><?php echo $registro->getClave(); ?></td>
                                <td><?php echo $registro->getDatos(); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="panel panel-default">

                    <div class="panel-body">
                        <div class="row">
                            <ul class="pager">
                                <li class="previous">
                                    <BUTTON <?php echo ($pagina == 0) ? 'disabled' : '' ?> name="first" value="first" title="Primera página" type="submit" class="btn btn-default"><<</BUTTON>
                                </li>
                                <li class="previous">
                                    <BUTTON <?php echo ($pagina == 0) ? 'disabled' : '' ?> name="prev" value="prev" title="Página anterior" type="submit" class="btn btn-default"><</BUTTON>
                                </li>
                                <li >
                                    <BUTTON disabled title="" type="submit" class="btn btn-default">Página <?php echo $pagina + 1 ?> de <?php echo $paginas + 1 ?></BUTTON>
                                </li>
                                <li class="next">
                                    <BUTTON <?php echo ($pagina == $paginas) ? 'disabled' : '' ?> name="next" value="next" title="Página siguiente" type="submit" class="btn btn-default">></BUTTON>
                                </li>
                                <li class="next">
                                    <BUTTON <?php echo ($pagina == $paginas) ? 'disabled' : '' ?> name="last" value="last" title="Última página" type="submit" class="btn btn-default">>></BUTTON>
                                </li>
                            </ul>
                        </div>
                        </filedset>
                        </form><br>
                        <div class="row">
                            <div class="col-md-12" align="center">    
                                <a href="<?php echo Utils::createLink('usuedit', array('id' => '')); ?>"><input type="button" name="boton" class="btn btn-primary" value="Ingresar un nuevo usuario" /></a>
                            </div>
                        </div>
                    </div>
                </div>