<?php
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2013 Gestión-e - Gestión Informática Eficiente. All rights reserved.
 *
 *
 */

?>

<h1>Muchas gracias por utilizar nuestro sistema</h1>

<p class="p">No divulgue su contraseña y recuerde actualizarla periódicamente.</p>

<script language="javascript">
    setTimeout(function(){window.location.assign("<?php echo $config['url'];?>");},3000);
</script>