<?php
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2013 Gestión-e - Gestión Informática Eficiente. All rights reserved.
 *
 *
 */

?>

<h1>
    Modificar niveles de autorización
</h1>

<?php if (!empty($errors)): ?>
    <ul class="errors">
        <?php foreach ($errors as $error): ?>
            <?php foreach ($error as $err): ?>
                <li><?php echo $err[1]; ?></li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<div class="col-md-3"></div>
<div class="col-md-6">
<form id="formulario" action="#" method="post"  role="form">
<div class="panel panel-default">
                <table  class="table table-striped table-hover table-condensed">
                    <thead>
                    <tr>
                    <th style="text-align:center" >Nivel</th>
                    <th >Importe máximo</th>
                    </tr>
                    </thead>
                    <tbody>

  
                    <tr>        
                    <td align="center">Un revisor</td>
                    <td><input type="text"  id="niveles-form[0]" name="niveles-form[0]" value="<?php echo $niveles[0]->getHasta() ?>"></td>
                    </tr>

                    <tr>        
                    <td align="center">Dos revisores</td>
                    <td><input type="text"  id="niveles-form[1]" name="niveles-form[1]" value="<?php echo $niveles[1]->getHasta() ?>"></td>
                    </tr>

                    <tr>        
                    <td align="center">Tres revisores</td>
                    <td><input type="text"  id="niveles-form[2]" name="niveles-form[2]" value="<?php echo $niveles[2]->getHasta() ?>"></td>
                    </tr>

                    </tbody>
                </table>
</div>  
<input type="submit" name="update" class="btn btn-primary btn-block" value="Actualizar" </input>
</form> 
</div>
<div class="col-md-3"></div>              
 

