<?php
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2013 Gestión-e - Gestión Informática Eficiente. All rights reserved.
 *
 *
 */

function error_field($title, array $errors) {
    foreach ($errors as $error) {
        /* @var $error Error */
        if ($error[0] == $title) {
            return ' error-field';
        }
    }
    return '';
}

?>

<h1>
    <?php if ($edit): ?>
        Modificar Usuario
    <?php else: ?>
        Ingresar nuevo Usuario
    <?php endif; ?>
</h1>

<?php if (!empty($errors)): ?>
    <ul class="errors">
        <?php foreach ($errors as $error): ?>
            <?php /* @var $error Error */ ?>
            <li><?php echo $error[1]; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Ingrese los datos del usuario</h3></div>
            <div class="panel-body">
                <form id="formulario" action="#" method="post" class="form-horizontal" role="form">
                    <fieldset>
                        <div class="form-group">
                            <label for="usuario" class="col-sm-4 control-label">Usuario:</label>
                            <div class="col-sm-8">
                                <input id="usuario" type="text" name="persona[usuario]" value="<?php echo Utils::escape($persona->getId()); ?>"
                                       class="form-control number<?php echo error_field('usuario', $errors); ?>" <?php if ($edit): ?> readonly<?php endif; ?>/>
                            </div></div>

                        <div class="form-group">
                            <label for="nombre" class="col-sm-4 control-label">Nombre:</label>
                            <div class="col-sm-8">
                                <input id="nombre" type="text" name="persona[nombre]" value="<?php echo Utils::escape($persona->getNombre()); ?>"
                                       class="form-control number<?php echo error_field('nombre', $errors); ?>"/>
                            </div></div>

                        <div class="form-group">
                            <label for="cuit" class="col-sm-4 control-label">Centro:</label>
                            <div class="col-sm-8">
                                <input id="cuit" type="number" min="0" max="999" name="persona[centro]" value="<?php echo Utils::escape($persona->getCentro()); ?>"
                                       class="form-control number<?php echo error_field('centro', $errors); ?>"/>
                            </div></div>
                        <div class="form-group">
                            <label for="mandante" class="col-sm-4 control-label">Sucursal:</label>
                            <div class="col-sm-8">
                                <input id="mandante" type="number" min="0" max="999" name="persona[sucursal]" value="<?php echo Utils::escape($persona->getSuc()); ?>"
                                       class="form-control number<?php echo error_field('sucursal', $errors); ?>"/>
                            </div></div>

                        <div class="form-group">
                            <label for="email" class="col-sm-4 control-label">email:</label>
                            <div class="col-sm-8">
                                <input id="email" type="email" name="persona[email]" value="<?php echo Utils::escape($persona->getEmail()); ?>"
                                       class="form-control number<?php echo error_field('email', $errors); ?>"/>
                            </div></div>

                        <div class="form-group">
                            <label for="estado" class="col-sm-4 control-label">Estado:</label>
                            <div class="col-sm-8">
                                <select id="estado" name="persona[estado]" class="form-control " >
                                    <?php foreach (Persona::getAllEstados() as $estado): ?>
                                        <option value="<?php echo $estado; ?>"
                                        <?php if ($estado == $persona->getEstado()): ?>
                                                    selected="selected"
                                                <?php endif; ?>
                                                ><?php echo $estado; ?></option>
                                            <?php endforeach; ?>
                                </select>
                            </div></div>
                    </div>
               </div>
          </div>



    <div class="col-lg-2">
        <div class="panel panel-default" >
            <div class="panel-heading"><h3 class="panel-title">Cámara Enviada</h3></div>
                <div class="panel-body">
                    <div class="row">
                        <table  class="table table-striped table-hover table-condensed">
                            <tbody>
                               <?php foreach (Usuario::getAllDescPermiso() as $key => $value): ?>
                               <?php if ($key[0]!='e') continue;?>
                                    <tr>
                                       <td>
                                           <div class="form-group">
                                               <div class="col-sm-offset-1 col-sm-11">
                                                   <div class="checkbox">
                                                       <label>
                                                       <input name="permiso[<?php echo $key; ?>]" type="checkbox"
                                                             <?php echo (isset($permisos[$key])) ? 'checked' : ''; ?>>
                                                                <?php echo $value; ?>
                                                       </label>
                                                    </div>
                                               </div>
                                           </div>
                                      </td>
                                   </tr>
                               <?php endforeach; ?>
                           </tbody>   
                        </table>    
                   </div>
              </div> 
        </div>
    </div>
    <div class="col-lg-2">
        <div class="panel panel-default" >
            <div class="panel-heading"><h3 class="panel-title">Cámara Recibida</h3></div>
                <div class="panel-body">
                    <div class="row">
                        <table  class="table table-striped table-hover table-condensed">
                            <tbody>
                               <?php foreach (Usuario::getAllDescPermiso() as $key => $value): ?>
                               <?php if ($key[0]!='r') continue;?>
                                    <tr>
                                       <td>
                                           <div class="form-group">
                                               <div class="col-sm-offset-1 col-sm-11">
                                                   <div class="checkbox">
                                                       <label>
                                                       <input name="permiso[<?php echo $key; ?>]" type="checkbox"
                                                             <?php echo (isset($permisos[$key])) ? 'checked' : ''; ?>>
                                                                <?php echo $value; ?>
                                                       </label>
                                                    </div>
                                               </div>
                                           </div>
                                      </td>
                                   </tr>
                               <?php endforeach; ?>
                           </tbody>   
                        </table>    
                   </div>
              </div> 
        </div>
    </div>
    <div class="col-lg-2">
        <div class="panel panel-default" >
            <div class="panel-heading"><h3 class="panel-title">Cartera</h3></div>
                <div class="panel-body">
                    <div class="row">
                        <table  class="table table-striped table-hover table-condensed">
                            <tbody>
                               <?php foreach (Usuario::getAllDescPermiso() as $key => $value): ?>
                               <?php if ($key[0]!='c') continue;?>
                                    <tr>
                                       <td>
                                           <div class="form-group">
                                               <div class="col-sm-offset-1 col-sm-11">
                                                   <div class="checkbox">
                                                       <label>
                                                       <input name="permiso[<?php echo $key; ?>]" type="checkbox"
                                                             <?php echo (isset($permisos[$key])) ? 'checked' : ''; ?>>
                                                                <?php echo $value; ?>
                                                       </label>
                                                    </div>
                                               </div>
                                           </div>
                                      </td>
                                   </tr>
                               <?php endforeach; ?>
                           </tbody>   
                        </table>    
                   </div>
              </div> 
        </div>
    </div>
    <div class="col-lg-2">
        <div class="panel panel-default" >
            <div class="panel-heading"><h3 class="panel-title">Administrador</h3></div>
                <div class="panel-body">
                    <div class="row">
                        <table  class="table table-striped table-hover table-condensed">
                            <tbody>
                               <?php foreach (Usuario::getAllDescPermiso() as $key => $value): ?>
                               <?php if ($key[0]!='a') continue;?>
                                    <tr>
                                       <td>
                                           <div class="form-group">
                                               <div class="col-sm-offset-1 col-sm-11">
                                                   <div class="checkbox">
                                                       <label>
                                                       <input name="permiso[<?php echo $key; ?>]" type="checkbox"
                                                             <?php echo (isset($permisos[$key])) ? 'checked' : ''; ?>>
                                                                <?php echo $value; ?>
                                                       </label>
                                                    </div>
                                               </div>
                                           </div>
                                      </td>
                                   </tr>
                               <?php endforeach; ?>
                           </tbody>   
                        </table>    
                   </div>
              </div> 
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-6" align="center">
        <input type="submit" name="cancel" value="Cancelar" class="btn btn-default" />
    </div>
    <div class="col-xs-6" align="center">
        <input type="submit" name="save" value="<?php echo $edit ? 'Modificar usuario' : 'Crear usuario'; ?>" class="btn btn-primary" />
    </div>
</fieldset>
</form>
</div>

